version: '2.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Build-Local.Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    restart: unless-stopped